# Generated by Django 5.0.1 on 2024-01-25 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('advisory_type', models.CharField(max_length=255)),
                ('advisory_number', models.CharField(max_length=255)),
                ('advisory_name', models.CharField(max_length=255)),
                ('tenant', models.CharField(default='', max_length=255)),
                ('iocs_matched', models.IntegerField(default=0)),
                ('iocs_list', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
