# Generated by Django 5.0.1 on 2024-01-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_result_datetime_remove_result_device_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(max_length=255)),
                ('to', models.TextField()),
                ('cc', models.TextField()),
                ('subject', models.CharField(default='', max_length=255)),
                ('url', models.URLField()),
                ('api_key', models.TextField()),
            ],
        ),
    ]
