# Generated by Django 5.0.1 on 2024-01-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_emailcredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcredentials',
            name='api_key',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='emailcredentials',
            name='cc',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailcredentials',
            name='to',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailcredentials',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
